[platformio]
default_envs = magtag

[env:magtag]
platform = espressif32
board = adafruit_magtag29_esp32s2
framework = espidf
monitor_speed = 115200
build_unflags = -fuse-cxa-atexit
lib_deps =
    lovyan03/LovyanGFX @ ^1.1.16

[env:native]
platform = native
test_framework = unity
build_flags =
    -DNATIVE
    -std=c11
    -include ${PROJECT_DIR}/test/mocks/esp_compat.h
    -I ${PROJECT_DIR}/include
    -I ${PROJECT_DIR}/test/mocks
